# Generated by Django 4.0.4 on 2022-12-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(max_length=13, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kpp',
            field=models.CharField(max_length=9, unique=True, verbose_name='КПП'),
        ),
    ]
