# Generated by Django 4.0.4 on 2022-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='customer_attorney',
            field=models.CharField(blank=True, max_length=200, verbose_name='Документ Заказчика'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='customer_signer',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО подписанта Заказчика'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='supplier_attorney',
            field=models.CharField(blank=True, max_length=200, verbose_name='Документ Поставщика'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='supplier_signer',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО подписанта Поставщика'),
        ),
    ]
