# Generated by Django 4.0.4 on 2022-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseorder',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
