# Generated by Django 4.0.4 on 2022-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_responseorder_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('issue', models.CharField(max_length=250, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение от пользователя',
                'verbose_name_plural': 'Сообщения от пользователей',
            },
        ),
    ]
