# Generated by Django 4.0.4 on 2023-01-02 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_agreement_customer_attorney_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
