# Generated by Django 4.0.4 on 2022-11-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusresponse',
            name='status',
            field=models.CharField(choices=[('On Approval', 'На согласовании'), ('Approved', 'Утвержден'), ('Not Approved', 'Не утвержден'), ('Cancelled', 'Отменен')], default='On Approval', max_length=120, verbose_name='Статус'),
        ),
    ]
