# Generated by Django 4.0.4 on 2023-01-03 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_agreement_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Создано'), ('Supplier-Signed', 'Подписан Поставщиком'), ('Customer-Signed', 'Подписан Заказчиком'), ('Signed', 'Документ подписан'), ('Cancelled', 'Отменен')], default='On Approval', max_length=120, verbose_name='Статус')),
                ('time_status', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.agreement', verbose_name='Соглашение')),
                ('user_initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь инициатор')),
            ],
        ),
    ]
