# Generated by Django 4.0.4 on 2023-01-05 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_statusagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='responseorder',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statusresponse',
            name='time_status',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
